Truncate msg descr before the DB insert.
jmalloc/ax pull request #164
Opened 2021-02-03 02:48 UTC by danilvpetrov

This PR truncates the ax message description before the insert to `ax_messagestore_message` table. This is required to fit into the size of `ax_messagestore_message.description` field.

2021-02-03 03:12 UTC, jmalloc commented on axmysql/messagestore/append.go
> +	// for details.
```suggestion
	// Truncate the message to 255 characters to fit within the column.
```

Just removing links to specific tags.

2021-02-03 03:13 UTC, jmalloc requested changes
Have you tried this branch, and if so does it fix the problem? I am not sure if there are other places where descriptions are persisted or not.

2021-02-03 07:33 UTC, danilvpetrov commented
> Have you tried this branch, and if so does it fix the problem? 

Ok, I tried it now. I had to introduce a message description length check to avoid out-of-bound panic when the description is less than 255 char. Apart from that it works as expected. 

> I am not sure if there are other places where descriptions are persisted or not.

Looks like `description` field is also used in [`ax_saga_snapshot` table](https://github.com/jmalloc/ax/blob/v0.4.0/axmysql/saga/snapshot.sql#L8) and [`ax_saga_instance ` table](https://github.com/jmalloc/ax/blob/v0.4.0/axmysql/saga/crud.sql#L8). It's probably worth placing truncation on these fields as well.

2021-02-03 07:48 UTC, danilvpetrov commented
I've added message description truncation for [`ax_saga_snapshot` table](https://github.com/jmalloc/ax/blob/v0.4.0/axmysql/saga/snapshot.sql#L8) and [`ax_saga_instance ` table](https://github.com/jmalloc/ax/blob/v0.4.0/axmysql/saga/crud.sql#L8) in https://github.com/jmalloc/ax/pull/164/commits/5b9da8f110a7fc0200e990fd41000f4073298247.

However, the one of the tests is currently failing due to the difference of in-memory presentation of PB messages. This happens due to the newer version of `protoc-gen-go` plugin. In addition, the version of the `Makefile` in this repository is older to what we normally use and does not observe the protobuf package version in `go.mod` file.

2021-02-03 22:23 UTC, jmalloc commented
Thanks man. Looks like I've got a few things to update there. If you don't mind just use this branch for now until I get a chance to do those protobuf/makefile/test updates, unless you feel like tackling them.

2021-02-04 03:15 UTC, danilvpetrov commented
Rebased from `master`. The coverage is failing as this PR is adding some more uncovered code.

2021-02-04 03:17 UTC, jmalloc approved these changes

2021-02-04 03:18 UTC, merged